### ISSUE TITLE
Kör backend och frontend med en och samma server

### ISSUE THREAD

**Issue by kirayatail** [gbgtech/gbgtechWeb#2]
Hitta ett sätt att kompilera frontend så att bara en server behöver köras. Det blir enklare för alla.

**Comment by lindskogen** [comment]
Maybe check this out https://github.com/christianalfoni/webpack-express-boilerplate/blob/master/server.js

**Comment by bark** [comment]
http://jlongster.com/Backend-Apps-with-Webpack--Part-I

**Comment by lindskogen** [comment]
Solved in 303d6c4f74e7754043d34ebcbb737179218e0f3c
